### ISSUE TITLE
A question about buffer inputs in Cacti tools

### ISSUE THREAD

**Issue by maryam-tavakoli** [maestro-project/maestro#10]
In the file BASE_constants.hpp in the directory: maestro-stable-master\lib\include\base, the variable l1_energy_multiplier is set to 1.68, and it seems that this variable is for reading and writing energy in L1 buffer. According to your paper, this value is calculated by Cacti tools.
Since we are working on a similar project, and we are interested to compare our results with yours, I would like to kindly ask you to send me your assumptions for L1 buffer in Cacti tools.

**Comment by tushar-krishna** [comment]
The energy multipliers are set relative the energy of a MAC. I believe these multipliers came from some preliminary analysis done using Cacti while MAESTRO was being developed assuming a CAM structure for the L1 buffers. But we dont have that analysis data anymore. The aim is for a user to plug in their own multipliers for the L1 and L2 buffers based on the sizes computed by MAESTRO.

**Comment by danielmanu93** [comment]
Hi Everyone, 
I’m new to MAESTRO. I’m still trying to figure out how to install and run MAESTRO for my project. I would really appreciate if I can get some help from anyone about how to set MAESTRO up on python. Thanks 


Sent from Yahoo Mail for iPhone


On Friday, October 2, 2020, 9:38 PM, Geonhwa <notifications@github.com> wrote:




Closed #10.

**Comment by ghjeong12** [comment]
Hi @danielmanu93 , could you open a new issue if it's not related to this thread?

**Comment by danielmanu93** [comment]
Okay sounds good! How do I open a new issue. Is there some kinda website where I can set up a new issue about my problem?. 

Sent from Yahoo Mail for iPhone


On Friday, October 2, 2020, 9:49 PM, Geonhwa <notifications@github.com> wrote:




Hi @danielmanu93 , could you open a new issue if it's not related to this thread?

**Comment by ghjeong12** [comment]
@danielmanu93 https://github.com/maestro-project/maestro/issues

**Comment by danielmanu93** [comment]
Hi. I have opened a new issue for my problem. What’s the next step though. 


Sent from Yahoo Mail for iPhone


On Friday, October 2, 2020, 9:54 PM, Geonhwa <notifications@github.com> wrote:




@danielmanu93 https://github.com/maestro-project/maestro/issues
