### ISSUE TITLE
Setting up MAESTRO on python 

### ISSUE THREAD

**Issue by danielmanu93** [maestro-project/maestro#11]
Hi Everyone, 

I’m new to MAESTRO. I’m still trying to figure out how to install and run MAESTRO for my project. I would really appreciate if I can get some help from anyone about how to set MAESTRO up on python. Thanks

**Comment by deadsupra** [comment]
It seems like you would have to compile it first usings scons (run `scons`. You will need scons).

As for running on python, you can use the os package to feed the maestro executable the flags/options.

For example:
`import os
os.system("./maestro --HW_file='<your hardware file>.m'")`
