### ISSUE TITLE
how do we print the help option?

### ISSUE THREAD

**Issue by paulrdelg** [maestro-project/maestro#13]
I am attempting to see all the complete options available (not just those listed in the example). However, I am unable to run the help print out.

I attempted the following:
`./maestro --help` or `./maestro -help` or `./maestro help`

It requests an input file, so I included them:
`./maestro --HW_file='<my hardware file>.m' --Mapping_file='<some mapping file>.m' --help`

However, it still does not recognize the help flag option. I see that is there code included (I believe in the option.hpp) for this feature.

**Comment by felix0901** [comment]
Hello @paulrdelg ,

It is not supported in the current version.
