### ISSUE TITLE
Extra Spaces in CSV header names

### ISSUE THREAD

**Issue by gannaramu** [maestro-project/maestro#14]
I dont know if this space in the CSV headers has a specific purpose but it took a while to figure out there was extra space in the Label while trying to handle data using pandas.
[DSE_csv_writer.hpp](https://github.com/maestro-project/maestro/blob/7723091f9721afd2574049b5f5faf52c7b6cd2f1/cost-model/include/design-space-exploration/DSE_csv_writer.hpp#L58)

**Comment by felix0901** [comment]
Hello @gannaramu,

Yes, you are right. There are some spacing in the current CSV header. There is no specific purpose. You could ignore it.
