### ISSUE TITLE
Modelling Clusters in MAESTRO

### ISSUE THREAD

**Issue by sarabjeetsingh007** [maestro-project/maestro#8]
Hi,
I'm trying to change the hardware descriptor file to model clusters/hierarchical PE arrays (something similar to your example at http://maestro.ece.gatech.edu/docs/build/html/hw_supported.html#hardware-supported)

However, I did not see any knobs for that. Could you help me understand how I'd model clusters in MAESTRO's hw descriptor file?

**Comment by felix0901** [comment]
Hello @sarabjeetsingh007,

Cluster is specified in the mapping file. Please see [these](https://github.com/maestro-project/maestro/tree/master/data/mapping) for multiple examples we provided.
