### ISSUE TITLE
Changing NoC parameters

### ISSUE THREAD

**Issue by sarabjeetsingh007** [maestro-project/maestro#9]
Hi,
I was playing around with the NoC parameters, and noted that when I change _noc_hops_ from 1 to 1024 and/or _noc_hop_latency_ from 1 to 1024 (or any other values) in the _run_example.sh_ file, my results doesn't change at all.
Can you help me understand why that is? My intuition is that once I increase my hop latency by a large amount, at least the runtime cycle count should increase. I did not see that.

**Comment by wxbbuaa2011** [comment]
I also change the number of PEs for alexnet， the alexnet.csv does not any change. This is unusual

**Comment by felix0901** [comment]
Hello @sarabjeetsingh007,

Could you try again on noc_hop_latency? I tested the latest version, and it works fine at the current version now.
What you say about latency is right, the runtime will increase.
